name: Issue Report
description: File an issue report.
title: "[Issue]: "
labels: ["issue"]
body:
  - type: textarea
    id: issue
    attributes:
      label: What is the issue?
      description: Please describe what the issue is.
      placeholder: ex. Game crashes when [...]
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please describe what steps to take to recreate the issue.
      placeholder: |
        Steps to reproduce the issue:
        1. Join a world
        2. Ride a pig
        3. Guide the pig off a cliff
        4. See crash report
    validations:
      required: true
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      options:
        - 1.21.1
        - 1.20.1
      default: 0
    validations:
      required: true
  - type: dropdown
    id: modloader
    attributes:
      label: Mod Loader
      description: What mod loader are you using?
      options:
        - Fabric
        - Forge
        - NeoForge
      default: 0
    validations:
      required: true
  - type: input
    id: nt-version
    attributes:
      label: Nostalgic Tweaks Version
      description: What Nostalgic Tweaks version are you on?
      placeholder: v#.#.#
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log and/or Crash Report
      description: Please upload your log or crash report to mclo.gs and paste the link here (or N/a).
      placeholder: N/a
    validations:
      required: true
  - type: textarea
    id: extras
    attributes:
      label: Additional Context
      description: Put any extra info you feel is neccessary here (or N/a).
      placeholder: N/a
  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement
      description: If you do not fill out this form correctly, your issue will be immediately closed.
      options:
        - label: I understand and have fully filled out the form, including the issue name.
          required: true
